name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BAZEL_VERSION: 7.2.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install required deps
      run: sudo apt-get install g++ unzip zip curl

    - name: Download bazel installer
      run: curl -OL https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh

    - name: Install bazel
      run: chmod +x bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh && sudo ./bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh && rm bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh

    - name: Bazel build all
      run: bazel build //:all

    - name: Upload libnink.* (x64)
      uses: actions/upload-artifact@v4.3.4
      with:
        # Artifact name
        name: Linux-nink-x64
        # A file, directory or wildcard pattern that describes what to upload
        path: bazel-bin/*
          